/**
 * Los 82 cantones oficiales de Costa Rica.
 * Código = provincia (1 dígito) + cantón (2 dígitos).
 * Fuente: División Territorial Administrativa de Costa Rica (INEC / TSE).
 */
export const CANTONES_CR: { codigo: string; nombre: string; provincia: string }[] = [
  // ── San José (1) ──
  { codigo: '101', nombre: 'San José', provincia: 'San José' },
  { codigo: '102', nombre: 'Escazú', provincia: 'San José' },
  { codigo: '103', nombre: 'Desamparados', provincia: 'San José' },
  { codigo: '104', nombre: 'Puriscal', provincia: 'San José' },
  { codigo: '105', nombre: 'Tarrazú', provincia: 'San José' },
  { codigo: '106', nombre: 'Aserrí', provincia: 'San José' },
  { codigo: '107', nombre: 'Mora', provincia: 'San José' },
  { codigo: '108', nombre: 'Goicoechea', provincia: 'San José' },
  { codigo: '109', nombre: 'Santa Ana', provincia: 'San José' },
  { codigo: '110', nombre: 'Alajuelita', provincia: 'San José' },
  { codigo: '111', nombre: 'Vázquez de Coronado', provincia: 'San José' },
  { codigo: '112', nombre: 'Acosta', provincia: 'San José' },
  { codigo: '113', nombre: 'Tibás', provincia: 'San José' },
  { codigo: '114', nombre: 'Moravia', provincia: 'San José' },
  { codigo: '115', nombre: 'Montes de Oca', provincia: 'San José' },
  { codigo: '116', nombre: 'Turrubares', provincia: 'San José' },
  { codigo: '117', nombre: 'Dota', provincia: 'San José' },
  { codigo: '118', nombre: 'Curridabat', provincia: 'San José' },
  { codigo: '119', nombre: 'Pérez Zeledón', provincia: 'San José' },
  { codigo: '120', nombre: 'León Cortés Castro', provincia: 'San José' },
  // ── Alajuela (2) ──
  { codigo: '201', nombre: 'Alajuela', provincia: 'Alajuela' },
  { codigo: '202', nombre: 'San Ramón', provincia: 'Alajuela' },
  { codigo: '203', nombre: 'Grecia', provincia: 'Alajuela' },
  { codigo: '204', nombre: 'San Mateo', provincia: 'Alajuela' },
  { codigo: '205', nombre: 'Atenas', provincia: 'Alajuela' },
  { codigo: '206', nombre: 'Naranjo', provincia: 'Alajuela' },
  { codigo: '207', nombre: 'Palmares', provincia: 'Alajuela' },
  { codigo: '208', nombre: 'Poás', provincia: 'Alajuela' },
  { codigo: '209', nombre: 'Orotina', provincia: 'Alajuela' },
  { codigo: '210', nombre: 'San Carlos', provincia: 'Alajuela' },
  { codigo: '211', nombre: 'Zarcero', provincia: 'Alajuela' },
  { codigo: '212', nombre: 'Sarchí', provincia: 'Alajuela' },
  { codigo: '213', nombre: 'Upala', provincia: 'Alajuela' },
  { codigo: '214', nombre: 'Los Chiles', provincia: 'Alajuela' },
  { codigo: '215', nombre: 'Guatuso', provincia: 'Alajuela' },
  { codigo: '216', nombre: 'Río Cuarto', provincia: 'Alajuela' },
  // ── Cartago (3) ──
  { codigo: '301', nombre: 'Cartago', provincia: 'Cartago' },
  { codigo: '302', nombre: 'Paraíso', provincia: 'Cartago' },
  { codigo: '303', nombre: 'La Unión', provincia: 'Cartago' },
  { codigo: '304', nombre: 'Jiménez', provincia: 'Cartago' },
  { codigo: '305', nombre: 'Turrialba', provincia: 'Cartago' },
  { codigo: '306', nombre: 'Alvarado', provincia: 'Cartago' },
  { codigo: '307', nombre: 'Oreamuno', provincia: 'Cartago' },
  { codigo: '308', nombre: 'El Guarco', provincia: 'Cartago' },
  // ── Heredia (4) ──
  { codigo: '401', nombre: 'Heredia', provincia: 'Heredia' },
  { codigo: '402', nombre: 'Barva', provincia: 'Heredia' },
  { codigo: '403', nombre: 'Santo Domingo', provincia: 'Heredia' },
  { codigo: '404', nombre: 'Santa Bárbara', provincia: 'Heredia' },
  { codigo: '405', nombre: 'San Rafael', provincia: 'Heredia' },
  { codigo: '406', nombre: 'San Isidro', provincia: 'Heredia' },
  { codigo: '407', nombre: 'Belén', provincia: 'Heredia' },
  { codigo: '408', nombre: 'Flores', provincia: 'Heredia' },
  { codigo: '409', nombre: 'San Pablo', provincia: 'Heredia' },
  { codigo: '410', nombre: 'Sarapiquí', provincia: 'Heredia' },
  // ── Guanacaste (5) ──
  { codigo: '501', nombre: 'Liberia', provincia: 'Guanacaste' },
  { codigo: '502', nombre: 'Nicoya', provincia: 'Guanacaste' },
  { codigo: '503', nombre: 'Santa Cruz', provincia: 'Guanacaste' },
  { codigo: '504', nombre: 'Bagaces', provincia: 'Guanacaste' },
  { codigo: '505', nombre: 'Carrillo', provincia: 'Guanacaste' },
  { codigo: '506', nombre: 'Cañas', provincia: 'Guanacaste' },
  { codigo: '507', nombre: 'Abangares', provincia: 'Guanacaste' },
  { codigo: '508', nombre: 'Tilarán', provincia: 'Guanacaste' },
  { codigo: '509', nombre: 'Nandayure', provincia: 'Guanacaste' },
  { codigo: '510', nombre: 'La Cruz', provincia: 'Guanacaste' },
  { codigo: '511', nombre: 'Hojancha', provincia: 'Guanacaste' },
  // ── Puntarenas (6) ──
  { codigo: '601', nombre: 'Puntarenas', provincia: 'Puntarenas' },
  { codigo: '602', nombre: 'Esparza', provincia: 'Puntarenas' },
  { codigo: '603', nombre: 'Buenos Aires', provincia: 'Puntarenas' },
  { codigo: '604', nombre: 'Montes de Oro', provincia: 'Puntarenas' },
  { codigo: '605', nombre: 'Osa', provincia: 'Puntarenas' },
  { codigo: '606', nombre: 'Quepos', provincia: 'Puntarenas' },
  { codigo: '607', nombre: 'Golfito', provincia: 'Puntarenas' },
  { codigo: '608', nombre: 'Coto Brus', provincia: 'Puntarenas' },
  { codigo: '609', nombre: 'Parrita', provincia: 'Puntarenas' },
  { codigo: '610', nombre: 'Corredores', provincia: 'Puntarenas' },
  { codigo: '611', nombre: 'Garabito', provincia: 'Puntarenas' },
  { codigo: '612', nombre: 'Puerto Jiménez', provincia: 'Puntarenas' },
  // ── Limón (7) ──
  { codigo: '701', nombre: 'Limón', provincia: 'Limón' },
  { codigo: '702', nombre: 'Pococí', provincia: 'Limón' },
  { codigo: '703', nombre: 'Siquirres', provincia: 'Limón' },
  { codigo: '704', nombre: 'Talamanca', provincia: 'Limón' },
  { codigo: '705', nombre: 'Matina', provincia: 'Limón' },
  { codigo: '706', nombre: 'Guácimo', provincia: 'Limón' },
];
